name: tensorflow_mp
channels:
  - defaults
dependencies:
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - openssl=1.1.1j
  - pip=21.0.1
  - python=3.8.8
  - setuptools=52.0.0
  - sqlite=3.35.1
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.36.2
  - wincertstore=0.2
  - pip:
    - absl-py==0.10.0
    - argon2-cffi==20.1.0
    - astunparse==1.6.3
    - async-generator==1.10
    - attrs==20.3.0
    - backcall==0.2.0
    - bleach==3.3.0
    - cachetools==4.2.1
    - cffi==1.14.5
    - chardet==4.0.0
    - cloudpickle==1.6.0
    - colorama==0.4.4
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.7.1
    - dill==0.3.3
    - dm-tree==0.1.5
    - entrypoints==0.3
    - future==0.18.2
    - gast==0.3.3
    - google-auth==1.28.0
    - google-auth-oauthlib==0.4.3
    - google-pasta==0.2.0
    - googleapis-common-protos==1.53.0
    - grpcio==1.36.1
    - h5py==2.10.0
    - idna==2.10
    - importlib-metadata==3.7.3
    - importlib-resources==5.1.2
    - ipykernel==5.5.0
    - ipython==7.21.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==2.11.3
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.12
    - jupyter-console==6.3.0
    - jupyter-contrib-core==0.3.3
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-core==4.7.1
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-latex-envs==1.4.6
    - jupyter-nbextensions-configurator==0.4.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - lxml==4.6.2
    - markdown==3.3.4
    - markupsafe==1.1.1
    - matplotlib==3.3.4
    - mistune==0.8.4
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.2
    - nest-asyncio==1.5.1
    - notebook==6.2.0
    - numpy==1.18.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - packaging==20.9
    - pandocfilters==1.4.3
    - parso==0.8.1
    - pickleshare==0.7.5
    - pillow==8.1.2
    - prometheus-client==0.9.0
    - promise==2.3
    - prompt-toolkit==3.0.17
    - protobuf==3.15.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pygments==2.8.1
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pywin32==300
    - pywinpty==0.5.7
    - pyyaml==5.4.1
    - pyzmq==22.0.3
    - qtconsole==5.0.3
    - qtpy==1.9.0
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - send2trash==1.5.0
    - six==1.15.0
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.3.1
    - tensorflow-datasets==4.2.0
    - tensorflow-estimator==2.3.0
    - tensorflow-metadata==0.28.0
    - tensorflow-probability==0.11.1
    - termcolor==1.1.0
    - terminado==0.9.3
    - testpath==0.4.4
    - tornado==6.1
    - tqdm==4.59.0
    - traitlets==5.0.5
    - typing-extensions==3.7.4.3
    - urllib3==1.26.4
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - zipp==3.4.1
